#!/bin/sh

ps -W | grep -q notepad++.exe

if [ $? -ne  0 ] ; then
  echo >&2 "no notepad++ is running."
  exit 1
fi

for x in "$@" ; do
  if [ ! -s "$x" ] ; then 
    echo creating new file "$x"
    echo >"$x"
  fi
  /cygdrive/c/athena_trunk/Notepad++/notepad++.exe "$(cygpath -w "$x")"
  echo opened "$x"
done

/cygdrive/c/athena_trunk/Notepad++/notepad++.exe