#!/bin/bash
alias sshes='grep Host ~/.ssh/config'
alias hosts='grep Host ~/.ssh/config'
alias hello='echo hello'

# pulled from some default bashrc somewhere
# alias less='less -r'                          # raw control characters
alias whence='type -a'                        # where, of a sort
alias grep='grep --color'                     # show differences in colour
alias egrep='egrep --color=auto'              # show differences in colour
alias fgrep='fgrep --color=auto'              # show differences in colour
# Some shortcuts for different directory listings
# alias ls='ls -hF --color=tty'                 # classify files in colour
alias dir='ls --color=auto --format=vertical'
alias vdir='ls --color=auto --format=long'
alias ll='ls -l'                              # long list
alias la='ls -A'                              # all but . and ..
alias l="ls -FGh"

# my own:
alias grepp='grep -P' # obselete when ack is available

alias nv=nvim
if [[ -n "$JP_LOGIN_UTILS_USE_NEOVIM" ]] ; then
  check-for-package nvim neovim
  alias vi="nvim"
  alias view="nvim -R"
else
  alias vi="vim"
  alias view="vim -R"
fi

# enables "fuck" command to correct your last command
if check-for-package thefuck ; then eval "$(thefuck --alias)" ; fi

# in case accidentally type vim commands into bash terminal
alias :q=true
alias ':h=:help'

# combined with vimpipe for sql, v useful
alias vsql='vim +"set ft=sql"'

alias pydoc='python3 -m pydoc'

# shellcheck disable=SC2154
if [[ "$jp_system_type" != linux ]] && check-for-package gsleep coreutils ; then
  alias sleep=gsleep
  _jp_awk='gawk'
else
  _jp_awk='awk'
fi

if check-for-package --optional zbarimg 'zbar for QR-code scanning' ; then
  alias qrdecode='zbarimg -Sdisable -Sqr.enable -q --raw'
fi

if check-for-package uniname 'uniutils (includes uniname for unicode analysis)'
then
  # suppress its extremely annoying paging behavior
  alias uniname='uniname -p'
fi

if [[ "$jp_system_type" == linux ]] ; then
  alias open='xdg-open'
fi

alias jq='jq --unbuffered'

function _jp_awk_alias() {
  local prg alias="${1?}" #aliascmd
  printf -v prg %q "$2"
  #printf -v aliascmd %q "$_jp_awk -e $prg"
# shellcheck disable=SC2139
  alias "$alias=$_jp_awk -e $prg"
}

_jp_awk_alias countlines '{print NR}'
# shellcheck disable=SC2016
_jp_awk_alias sumlines 'BEGIN {S=0.0} {S+=$1} END {print S}'
# shellcheck disable=SC2016
_jp_awk_alias awk1 '{print $1}'

# shellcheck disable=SC2016
_jp_awk_alias sumlinesbygroup '
  NR == 1 { S = 0.0 ; OLDKEY = $1 }
  NR > 1 && OLDKEY != $1 { print OLDKEY, S ; S = 0.0 ; OLDKEY = $1 }
  { S += $2 }
  END { print OLDKEY, S }
'
unset -f _jp_awk_alias
