#!/bin/bash
alias sshes='grep Host ~/.ssh/config'
alias hosts='grep Host ~/.ssh/config'
alias hello='echo hello'

# pulled from some default bashrc somewhere
# alias less='less -r'                          # raw control characters
alias whence='type -a'                        # where, of a sort
alias grep='grep --color'                     # show differences in colour
alias egrep='egrep --color=auto'              # show differences in colour
alias fgrep='fgrep --color=auto'              # show differences in colour
# Some shortcuts for different directory listings
# alias ls='ls -hF --color=tty'                 # classify files in colour
alias dir='ls --color=auto --format=vertical'
alias vdir='ls --color=auto --format=long'
alias ll='ls -l'                              # long list
alias la='ls -A'                              # all but . and ..
alias l="ls -FGh"

# my own:
alias grepp='grep -P' # obselete when ack is available
alias ackp="ack --type=python"
alias ackh="ack --type=html"
alias ackn="ack --nopager" # suppress pager
alias ackl='ack --pager="less -FRX"' # force pager
alias vi="vim"
alias view="vim -R"

# enables "fuck" command to correct your last command
if check-for-package thefuck ; then eval "$(thefuck --alias)" ; fi

# in case accidentally type vim commands into bash terminal
alias :q=true
alias ':h=:help'

# combined with vimpipe for sql, v useful
alias vsql='vim +"set ft=sql"'

alias pydoc='python3 -m pydoc'

if check-for-package gsleep coreutils ; then
  alias sleep=gsleep
fi

if check-for-package --optional zbarimg 'zbar for QR-code scanning' ; then
  alias qrdecode='zbarimg -Sdisable -Sqr.enable -q --raw'
fi
