#!/bin/bash

source_pragma_once "$MY_BASHRC_D"/path

if check-for-package --optional brew ; then
  source_pragma_once "$(brew --prefix)"/etc/bash_completion
fi

gitcompletion=/usr/local/etc/bash_completion.d/git-completion.bash
[[ -r "$gitcompletion" ]] && source_pragma_once "$gitcompletion"

# the remainder of this is snippets taken from vim wikia for completing on
# vim -t. These were apparently defective at some point and I had to comment
# them out. Leaving the functions in case this is wanted in the future.

# from vim wikia
_vim_search() {
    ex -N -u NONE -i NONE \
          -c 'let &tags="'"$2"'"' \
          -c 'echo "\\n"' \
          -c 'for tag in taglist("^".escape("'"$1"'","."))|echo tag["name"]|endfor' \
          -cq \
        | tr -s '\r' '\n' | grep '^[a-zA-Z_]'
}

_vim() {
    local cur prev

    COMPREPLY=()
    cur=${2}
    prev=${3}

    case "${prev}" in
        -t)
            local tagsdir=$PWD
            while [[ "$tagsdir" && ! -f "$tagsdir/tags" ]]; do
                tagsdir=${tagsdir%/*}
            done
            [[ -f "$tagsdir/tags" ]] || return

            mapfile -t COMPREPLY < <(_vim_search "$cur" "$tagsdir/tags" )
            return
            ;;
        *)
            # Perform usual completion mode
            ;;
    esac
}


#excludelist='*.@(o|O|so|SO|so.!(conf)|SO.!(CONF)|a|A|rpm|RPM|deb|DEB|gif|GIF|jp?(e)g|JP?(E)G|mp3|MP3|mp?(e)g|MP?(E)G|avi|AVI|asf|ASF|ogg|OGG|class|CLASS)'

# TODO run conditioned on an envvar that can be set before sourcing in .bashrc

# complete -F _vim_search -f -X "${excludelist}" vi vim
# complete -f vi vim  # restore default  # but apparently this doesn't work either...
# complete -r vi vim
