#!/bin/bash

source_pragma_once ~/.sleeprc ##enable the builtin version of sleep

function addhost(){
    for x in "$@" ; do
      echo adding $x
      sed "s/%HOST%/$x/" ~/.ssh/config_template >>~/.ssh/config
    done
}

# obselete
function cdsrc() {
  local envi="$1" ; shift
  c "$SRC/${envi}/projects" "$@"
  return $?
}


function c(){
  local DIR="$1"
  shift
  if [[ ! -d "$DIR" ]] ; then
    mkdir -pv "$DIR" >&2
    local RESULT=$?
    [[ $RESULT == 0 ]] || return $RESULT
  fi
  echo "$DIR" >&2
  if [[ -z "$*" ]] ; then
    cd "$DIR"
  else
    ( cd "$DIR" && "$@" )
  fi
}

# Mac-only
function ppid() {
  local PID=$$ ; ps -p $(cat /proc/$PID/ppid)
}

function create_alias() {
  for x ; do
    echo alias "'$x'" >>~/bashrc.d/alias
    source ~/bashrc.d/alias
  done
}

function code() {
  local suff="${1:-wc}"
  local folders=(~/code/*"$suff")
  local numf="${#folders[@]}"
  case "$numf" in
    1) ;;
    *)
        echo >/dev/tty "$numf" folders found for \*"$suff", please be more specific:
	for folder in "${folders[@]}" ; do
           echo >/dev/tty -e "\\t$folder"
        done
	return 2 ;;
  esac
  for folder in "${folders[@]}" ; do
    [[ -d "$folder" ]] && c "$folder" || \
         { echo >/dev/tty 'No folder found for *'"$suff" ; return 1 ;}
    [[ ! -d .git ]] || git status
  done
}

function space() {
  local lines=${LINES}
  local arg="${1:-0}"
  local neg=""
  local div=""
  [[ -n "$1" && "$arg" != -* ]] || { neg=x ; arg=${arg##-} ; }
  [[ "${arg}" != /* ]] || { div=x ; arg="${arg##/}" ; }
  [[ "${arg}" != *[^0-9]* ]] || return 1 ;
  [[ -z "$div" ]] || arg="$((LINES / arg))"
  [[ -z "$neg" ]] && lines="$arg" || lines="$((lines - ${arg}))"
  seq "$lines" | tr -dC \\n
}

# quickly access vimrc.
# If you source another vimrc from this one, do "vimrc 1" to go straight to it.
# "vimrc 2", "vimrc 3", etc to go to the second or third sourced file
function vimrc() {
  local OPTS=()
  if [[ "$#" != 0 ]] ; then
    local n
    case "$1" in
      0|*[^0-9]*) n=1 ;;
      *)  n="$1" ;;
    esac
    while [[ "$((n--))" > 0 ]] ; do
      OPTS=("${OPTS[@]}" '+/^source')
    done
    OPTS=("${OPTS[@]}" '+normal $gf')
  fi
  vim ~/.vimrc "${OPTS[@]}"
}

# quickly access git help
function :help() {
  vim "+help $1" "+2close"
}

function py() {
  if [[ -x venv/bin/python ]] ; then venv/bin/python "$@" ; else  python "$@" ; fi
}

function pi() {
  if [[ -x venv/bin/pip ]] ; then venv/bin/pip "$@" ; else  pip "$@" ; fi
}
