#!/bin/bash
# shellcheck disable=SC1090

if [[ "$TERM_PROGRAM" == *iTerm* ]] ; then
  source_pragma_once ~/.iterm2_shell_integration.bash
fi

source_pragma_once "$MY_BASHRC_D"/path

if [[ -n "$ITERM_SHELL_INTEGRATION_INSTALLED" ]] ; then
  append-path ~/.iterm2
  function jp_iterm_send_prompt() {
    iterm2_begin_osc
    printf '%s;%s' "$1" "$2"
    iterm2_end_osc
  }

  function iterm_growl() {
    jp_iterm_send_prompt 9 "$1"
  }

  function remind() {
    sleeptime="${1:?usage: remind SLEEPTIME[m|s] message text}"
    (
      sleep "$sleeptime"
      shift
      iterm_growl "$*"
      printf '\n\nReminder:\n%s\n\n\n' "$*"
      it2attention fireworks
    ) &
  }

  function iterm_badge_format() {
    jp_iterm_send_prompt 1337 "SetBadgeFormat=$(echo -n "$1" | base64)"
  }

  iterm_badge_format '(\(user.tty)) \(user.badge)'
  iterm2_set_user_var tty "$(basename "$(tty)")"
  iterm2_set_user_var badge ''

  function badge() {
    iterm2_set_user_var badge "$*"
  }
fi
