#!/bin/bash

# utilities to easily add paths to your PATH.
# Each one checks for duplicate entries and that the directory exists.

function _can_add() {
  [[ -n "$1" && "$#" == 1 ]] && [[  "$PATH" == *?:"$1":?* || "$PATH" == "$1":?*
                                    || "$PATH" == *?:"$1" || ! -d "$1" ]]
}

function prepend-path() {
  for x ; do _can_add "$x" || export PATH="$x":"$PATH" ; done
}

function append-path() {
  for x ; do _can_add "$x" || export PATH="$PATH":"$x" ; done
}

prepend-path /usr/local/bin ~/bin
source_pragma_once $HOME/bashrc.d/*-path
echo -n PATH= ; printenv PATH

