#!/bin/bash
# ssh-agent
# shamelessly adapted (plagiarized) from some stack exchange thread

source_pragma_once ~/bashrc.d/env

SSH_ENV="$HOME/.ssh/agent-setup"
SSH_ENV_LOCK="$HOME/.ssh/agent-setup-lock"

function start-agent {
  echo executing start-agent
     if mkdir "$SSH_ENV_LOCK" >/dev/null 2>&1 ; then
       echo "Initialising new SSH agent..."
       /usr/bin/ssh-agent > "${SSH_ENV}"
       echo succeeded
       chmod 600 "${SSH_ENV}"
       . "${SSH_ENV}" #> /dev/null
       /usr/bin/ssh-add
     else
       echo somebody beat me to the punch, trying again
       check-env-file || start-agent
     fi
}

function check-env-file() {
  echo executing check-env-file
    if [[ -f "${SSH_ENV}" ]] ; then
      source "${SSH_ENV}"
    else
      rm -rf "$SSH_ENV" "$SSH_ENV_LOCK"
      return 1
    fi
    # ps ${SSH_AGENT_PID} doesn't work under cywgin
    echo checking for agent pid "$SSH_AGENT_PID"
    if ps ${CYGWIN:+-p} ${SSH_AGENT_PID} | grep -m1 ssh-agent$ > /dev/null
    then
      echo "previous agent ${SSH_AGENT_PID} is still running"
    else
      echo clearing out-of-date settings files
      rm -rf "${SSH_ENV}" "$SSH_ENV_LOCK"
      return 1
    fi
}

# Source SSH settings, if applicable

check-env-file || start-agent
