#!/bin/bash
# ssh-agent
# shamelessly adapted (plagiarized) from some stack exchange thread

source_pragma_once ~/bashrc.d/env

SSH_ENV="$HOME/.ssh/environment"

function random-wait() {
    local secs="$((RANDOM % 7))"
    case "$secs" in
      [0123]) ;;
      *) secs=4 ;;
    esac
    sleep "$secs"
}

function start-agent {
     echo "Initialising new SSH agent..."
     /usr/bin/ssh-agent > "${SSH_ENV}"
     echo succeeded
     chmod 600 "${SSH_ENV}"
     . "${SSH_ENV}" #> /dev/null
     /usr/bin/ssh-add
}

function check-env-file() {
    [[ -f "${SSH_ENV}" ]] && source "${SSH_ENV}" || return 1
    # ps ${SSH_AGENT_PID} doesn't work under cywgin
    if ps ${CYGWIN:+-p} ${SSH_AGENT_PID} | grep -m1 ssh-agent$ > /dev/null ; then
      echo "previous agent ${SSH_AGENT_PID} is still running"
    else
      rm -f "${SSH_ENV}"
      return 1
    fi
}

# Source SSH settings, if applicable

while ! check-env-file ; do
     random-wait
     check-env-file || start-agent
done
